spring:
  application:
    name: donation-app

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

server:
  port: ${SERVER_PORT:8080}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:}

info:
  app:
    version: ${USER_DATA_SERVICE_VERSION:0.1.0-SNAPSHOT}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.data.r2dbc: INFO
    io.r2dbc: INFO
